# 2017 May 25
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: ruby
rvm:
  - "2.2"
install:
  - gem install travis --no-rdoc --no-ri
script:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/travis-another.bash)"
# travis env set OTHER_REPO_SLUG 'bevry/website' --public
# travis env set GITHUB_TRAVIS_TOKEN "$GITHUB_TRAVIS_TOKEN"

# Custom Notifications
# travis encrypt "$TRAVIS_NOTIFICATION_EMAIL" --add notifications.email.recipients
# travis encrypt "$SLACK_SUBDOMAIN:$SLACK_TRAVIS_TOKEN#updates" --add notifications.slack
notifications:
  email:
    recipients:
      secure: bQrOlL3jkqeOJp6rjUrY2p1kbw5Yrknv0hmGjU1if7lMhBjnEpaksRSBqEPDJlIFfv0i4VmN2BDt8BkhrUCJ2NxRYt5Os+8rVzz55Dw08Yq2qwyg3VnTtJBiCXgmtm6FVJxBbHhHF1zMeET3r9vK3Po1WTx67nuYcITu2NzntBU=
  slack:
    secure: PiSiUfXw/pYDvlvIlLKXyhu2AgtgxmkOHYRqBlFiMIb58w7ZKHgneTHw58dqs/M4GPMmLvLN972/fp4vNaZmlL35IkFSF8FUC6WA2GbXfEimXIB53HrK+5+tk7ZxtBVsSQ6pC5ZJHnPCw2lCAzGjy8aMbyzsfxFlR7DLE5d3lyA=
